
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alivecommerce_development
  username: postgres
  password: root
  host: localhost

test:
  <<: *default
  database: alivecommerce_test
  username: postgres
  password: root
  host: localhost

production:
  <<: *default
  database: alivecommerce_production
  username: attendz
  password: <%= ENV['ALIVE_DATABASE_PASSWORD'] %>
